name: build-test-recipe
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'
      - 'master-next'
    paths:
      - '**.bb'
      - '**.inc'
jobs:
  changed-recipes:
    name: Get changed recipes
    runs-on: ubuntu-latest
    outputs:
      recipes: ${{ steps.diff.outputs.recipes }}
    steps:
    - uses: actions/checkout@v2
    - name: Diff files and set variables
      id: diff
      run: |
        # See https://github.community/t/check-pushed-file-changes-with-git-diff-tree-in-github-actions/17220/10
        if [ $GITHUB_BASE_REF ]; then
          # Pull Request
          git fetch origin $GITHUB_BASE_REF --depth=1
          export DIFF=$( git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA )
          echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
        else
          # Push
          git fetch origin ${{ github.event.before }} --depth=1
          export DIFF=$( git diff --name-only ${{ github.event.before }} $GITHUB_SHA )
          echo "Diff between ${{ github.event.before }} and $GITHUB_SHA"
        fi
        echo "$DIFF"
        echo "diff=$( echo "$DIFF" | tr -d '\n' )" >> $GITHUB_OUTPUT
        # Get recipe names
        export RECIPES=$( echo "$DIFF" | sed 's!.*/!!' | sed 's!.bb!!' | sed 's!_.*!!' | sort | uniq | sed -z $'s/\\\n/ /g')
        echo "Changed recipes"
        echo "$RECIPES"
        echo "recipes=$( echo "$RECIPES" | tr -d '\n' )" >> $GITHUB_OUTPUT        
        # TODO if nothing is found, build, test everything that should work
        # THINGS_TO_EXCLUDE="! -name neo-ai-tv* ! -name corretto-17-bin* ! -name corretto-21-bin* ! -name corretto-8-bin* ! -name firecracker-bin* ! -name jailer-bin*" &&
        # META_AWS_PACKAGES=$(find ../layers/sw/meta-aws -name *.bb -type f \( ${THINGS_TO_EXCLUDE} \) | sed 's!.*/!!' | sed 's!.bb!!' | sed 's!_.*!!' | sort | uniq | sed -z $'s/\\\n/ /g') &&
      
  build-test:
    name: Build, Test
    needs: changed-recipes
    strategy:
      fail-fast: false
      matrix:
        machine:
          - qemuarm
          - qemuarm64
          - qemux86-64          
    runs-on: codebuild-${{ vars.CODEBUILD_RUNNER_NAME }}-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout meta-aws
        uses: actions/checkout@v4
        with:
            path: ${{ github.workspace }}/meta-aws
      - name: Checkout meta-oe
        uses: actions/checkout@v4
        with:
          repository: openembedded/meta-openembedded
          path: ${{ github.workspace }}/meta-openembedded
      - name: Checkout poky
        run: |
          git clone git://git.yoctoproject.org/poky --single-branch  ${{ github.workspace }}/poky
      - name: Run build
        run: |
           apt-get -y install sudo
           chown yoctouser /sstate-cache
           chown yoctouser /downloads
           chown -R yoctouser .
           sysctl vm.mmap_min_addr=65536
           env
           sudo -u yoctouser bash -c '\
           whoami && \
           id && \
           cd  ${{ github.workspace }} &&
           source poky/oe-init-build-env build
           bitbake-layers add-layer ../meta-openembedded/meta-oe &&
           bitbake-layers add-layer ../meta-openembedded/meta-python &&
           bitbake-layers add-layer ../meta-openembedded/meta-networking &&
           bitbake-layers add-layer ../meta-openembedded/meta-multimedia &&
           bitbake-layers add-layer ../meta-aws &&
           export SSTATE_DIR=/sstate-cache && \
           export DL_DIR=/downloads && \
           export MACHINE=${{ matrix.machine }} && \
           export BB_ENV_PASSTHROUGH_ADDITIONS="$BB_ENV_PASSTHROUGH_ADDITIONS SSTATE_DIR DL_DIR" && \
           bitbake ${{ needs.changed-recipes.outputs.recipes }} '
      
