name: Build and test all supported branches

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  trigger-branch-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger workflows in other branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branches=("scarthgap-next" "kirkstone-next" "styhead-next")
          for branch in "${branches[@]}"; do
            gh workflow run build-test-recipe.yml --ref $branch
          done
          
      - name: Wait for branch workflows to complete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branches=("develop" "feature-branch")
          max_attempts=90  # Maximum 90 min exec time
          
          for attempt in $(seq 1 $max_attempts); do
            all_completed=true
            for branch in "${branches[@]}"; do
              status=$(gh run list --workflow=build-test-recipe.yml --branch=$branch --limit 1 --json status --jq '.[0].status')
              if [ "$status" != "completed" ]; then
                all_completed=false
                break
              fi
            done
            
            if $all_completed; then
              echo "All branch workflows have completed."
              break
            fi
            
            if [ $attempt -eq $max_attempts ]; then
              echo "Timeout waiting for workflows to complete."
              exit 1
            fi
            
            echo "Waiting for workflows to complete... (Attempt $attempt/$max_attempts)"
            sleep 60
          done

      - name: Report status
        run: |
          echo "All branch workflows have completed."
          for branch in "${branches[@]}"; do
            conclusion=$(gh run list --workflow=build-test-recipe.yml --branch=$branch --json conclusion --jq '.[0].conclusion')
            echo "Branch $branch workflow conclusion: $conclusion"
          done
