name: yocto-check-layer

on:
  pull_request:
    branches:
      - '*-next'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: get yocto release name
        id: get-yocto-release-name
        run: |
            release_name=$(echo ${{github.event.pull_request.base.ref}} | cut -d- -f1)
            echo "{release_name}={$release_name}" >> $GITHUB_OUTPUT
      - name: install required packages to run yocto-check-layer
        run: | 
          sudo apt-get -y install file gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm python3-subunit mesa-common-dev zstd liblz4-tool locales
          echo "en_US.UTF-8 UTF-8" | sudo tee --append /etc/locale.gen
          sudo locale-gen
      - name: checkout meta-aws branch to test
        uses: actions/checkout@v3
        with:
          path: yocto_checklayer
      - name: checkout meta-oe
        uses: actions/checkout@v3
        with:
          repository: https://github.com/openembedded/meta-openembedded.git
          path: yocto_checklayer
          ref: ${{steps.get-yocto-release-name.outputs.release_name}}
      - name: checkout poky
        uses: actions/checkout@v3
        with:
          repository: git://git.yoctoproject.org/poky
          path: yocto_checklayer
          ref: ${{steps.get-yocto-release-name.outputs.release_name}}          
      - name: run yocto-check-layer
        run: |
          cd yocto_checklayer/         
          source poky/oe-init-build-env build
          yocto-check-layer ../meta-aws/ --dependency ../meta-openembedded/meta-oe/ ../meta-openembedded/meta-python/  ../meta-openembedded/meta-networking --output-log ycl-check_meta-aws.log --debug --no-auto --no-auto-dependency
          touch ycl-check_meta-aws.log
      - name: save test result
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ycl-check_meta-aws
          path: yocto_checklayer/build/ycl-check_meta-aws.log
